---
title: "ladies"
author: "Anna Quaglieri"
date: "23/10/2017"
output: html_document
---

```{r setup, include=TRUE,cache=TRUE}
knitr::opts_chunk$set(echo = TRUE,dev = "pdf")
```

```{r include=FALSE,cache=TRUE}
library(readr)
ladies_fields <- read.csv("ladies_fields.csv")

skills <- ladies_fields$fields
skills <- gsub(","," ",skills)
skills <- tolower(skills)
skills <- skills[!is.na(skills)]
skills <- gsub(")","",skills)

library(tm)
library(RColorBrewer)
# Create objects for the worldcloud
corpus <- tm::Corpus(tm::VectorSource(skills))

# Create termdocoumentmatrix
tdm <- tm::TermDocumentMatrix(corpus,
                    control = list(removePunctuation = TRUE,
        stopwords = c("machine", "learning", tm::stopwords("english")),
        removeNumbers = TRUE, tolower = TRUE))   
tdm

# define tdm as matrix
dm <- as.matrix(tdm)
# get word counts in decreasing order
word_freqs <- sort(rowSums(dm), decreasing=TRUE) 
# create a data frame with words and their frequencies
dm <- data.frame(word = names(word_freqs), freq = word_freqs)

knitr::kable(head(dm))
# Plot the word cloud
wordcloud::wordcloud(dm$word, dm$freq, min.freq=1,random.order=FALSE, max.words = 100, colors=brewer.pal(8, "Dark2"))
```

## Event's abstract


```{r world_cloud,cache=TRUE}
Previous_Meetup_Details <- read_csv("Previous Meetup Details.csv")

abstract <- Previous_Meetup_Details$Abstract
abstract <- gsub(","," ",abstract)
abstract <- tolower(abstract)
abstract <- abstract[!is.na(abstract)]
abstract <- gsub(")","",abstract)

library(tm)
library(RColorBrewer)
# Create objects for the worldcloud
corpus <- tm::Corpus(tm::VectorSource(abstract))

# Create termdocoumentmatrix
tdm <- tm::TermDocumentMatrix(corpus,
                    control = list(removePunctuation = TRUE,
        stopwords = c("machine", "learning", tm::stopwords("english")),
        removeNumbers = TRUE, tolower = TRUE))   
tdm

# define tdm as matrix
dm <- as.matrix(tdm)
# get word counts in decreasing order
word_freqs <- sort(rowSums(dm), decreasing=TRUE) 
# create a data frame with words and their frequencies
dm <- data.frame(word = names(word_freqs), freq = word_freqs)

knitr::kable(head(dm))
dm <- dm[-c(2,5),]
dm <- dm[-6,]
# Plot the word cloud
wordcloud::wordcloud(dm$word, dm$freq, min.freq=3,random.order=FALSE, max.words = 100, colors=brewer.pal(8, "Dark2"))


```


